// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Account) AccOwner(ctx context.Context) (*Customer, error) {
	result, err := a.Edges.AccOwnerOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryAccOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (b *Booking) BookingFlight(ctx context.Context) (*Flight, error) {
	result, err := b.Edges.BookingFlightOrErr()
	if IsNotLoaded(err) {
		result, err = b.QueryBookingFlight().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (b *Booking) BookingOwner(ctx context.Context) (*Customer, error) {
	result, err := b.Edges.BookingOwnerOrErr()
	if IsNotLoaded(err) {
		result, err = b.QueryBookingOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (c *Customer) Accounts(ctx context.Context) (result []*Account, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = c.NamedAccounts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = c.Edges.AccountsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = c.QueryAccounts().All(ctx)
	}
	return result, err
}

func (c *Customer) Bookings(ctx context.Context) (result []*Booking, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = c.NamedBookings(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = c.Edges.BookingsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = c.QueryBookings().All(ctx)
	}
	return result, err
}

func (f *Flight) BelongsTo(ctx context.Context) (result []*Booking, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = f.NamedBelongsTo(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = f.Edges.BelongsToOrErr()
	}
	if IsNotLoaded(err) {
		result, err = f.QueryBelongsTo().All(ctx)
	}
	return result, err
}
