// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mock_project/ent/account"
	"mock_project/ent/booking"
	"mock_project/ent/customer"
	"mock_project/ent/flight"
	"mock_project/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[4].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[5].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	bookingFields := schema.Booking{}.Fields()
	_ = bookingFields
	// bookingDescTotalCost is the schema descriptor for total_cost field.
	bookingDescTotalCost := bookingFields[1].Descriptor()
	// booking.TotalCostValidator is a validator for the "total_cost" field. It is called by the builders before save.
	booking.TotalCostValidator = bookingDescTotalCost.Validators[0].(func(float64) error)
	// bookingDescTotalTicket is the schema descriptor for total_ticket field.
	bookingDescTotalTicket := bookingFields[2].Descriptor()
	// booking.DefaultTotalTicket holds the default value on creation for the total_ticket field.
	booking.DefaultTotalTicket = bookingDescTotalTicket.Default.(int)
	// booking.TotalTicketValidator is a validator for the "total_ticket" field. It is called by the builders before save.
	booking.TotalTicketValidator = bookingDescTotalTicket.Validators[0].(func(int) error)
	// bookingDescCreatedAt is the schema descriptor for created_at field.
	bookingDescCreatedAt := bookingFields[4].Descriptor()
	// booking.DefaultCreatedAt holds the default value on creation for the created_at field.
	booking.DefaultCreatedAt = bookingDescCreatedAt.Default.(func() time.Time)
	// bookingDescUpdatedAt is the schema descriptor for updated_at field.
	bookingDescUpdatedAt := bookingFields[5].Descriptor()
	// booking.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	booking.DefaultUpdatedAt = bookingDescUpdatedAt.Default.(func() time.Time)
	// booking.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	booking.UpdateDefaultUpdatedAt = bookingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookingDescID is the schema descriptor for id field.
	bookingDescID := bookingFields[0].Descriptor()
	// booking.DefaultID holds the default value on creation for the id field.
	booking.DefaultID = bookingDescID.Default.(func() uuid.UUID)
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescName is the schema descriptor for name field.
	customerDescName := customerFields[1].Descriptor()
	// customer.NameValidator is a validator for the "name" field. It is called by the builders before save.
	customer.NameValidator = customerDescName.Validators[0].(func(string) error)
	// customerDescCitizenID is the schema descriptor for citizen_id field.
	customerDescCitizenID := customerFields[2].Descriptor()
	// customer.CitizenIDValidator is a validator for the "citizen_id" field. It is called by the builders before save.
	customer.CitizenIDValidator = func() func(string) error {
		validators := customerDescCitizenID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(citizen_id string) error {
			for _, fn := range fns {
				if err := fn(citizen_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// customerDescPhone is the schema descriptor for phone field.
	customerDescPhone := customerFields[3].Descriptor()
	// customer.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	customer.PhoneValidator = customerDescPhone.Validators[0].(func(string) error)
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[7].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
	// customerDescUpdatedAt is the schema descriptor for updated_at field.
	customerDescUpdatedAt := customerFields[8].Descriptor()
	// customer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	customer.DefaultUpdatedAt = customerDescUpdatedAt.Default.(func() time.Time)
	// customer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	customer.UpdateDefaultUpdatedAt = customerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() uuid.UUID)
	flightFields := schema.Flight{}.Fields()
	_ = flightFields
	// flightDescFlightCode is the schema descriptor for flight_code field.
	flightDescFlightCode := flightFields[1].Descriptor()
	// flight.FlightCodeValidator is a validator for the "flight_code" field. It is called by the builders before save.
	flight.FlightCodeValidator = flightDescFlightCode.Validators[0].(func(string) error)
	// flightDescFrom is the schema descriptor for from field.
	flightDescFrom := flightFields[2].Descriptor()
	// flight.FromValidator is a validator for the "from" field. It is called by the builders before save.
	flight.FromValidator = flightDescFrom.Validators[0].(func(string) error)
	// flightDescTo is the schema descriptor for to field.
	flightDescTo := flightFields[3].Descriptor()
	// flight.ToValidator is a validator for the "to" field. It is called by the builders before save.
	flight.ToValidator = flightDescTo.Validators[0].(func(string) error)
	// flightDescDuration is the schema descriptor for duration field.
	flightDescDuration := flightFields[6].Descriptor()
	// flight.DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	flight.DurationValidator = flightDescDuration.Validators[0].(func(int) error)
	// flightDescCapacity is the schema descriptor for capacity field.
	flightDescCapacity := flightFields[7].Descriptor()
	// flight.DefaultCapacity holds the default value on creation for the capacity field.
	flight.DefaultCapacity = flightDescCapacity.Default.(int)
	// flight.CapacityValidator is a validator for the "capacity" field. It is called by the builders before save.
	flight.CapacityValidator = flightDescCapacity.Validators[0].(func(int) error)
	// flightDescAvailableSeat is the schema descriptor for available_seat field.
	flightDescAvailableSeat := flightFields[8].Descriptor()
	// flight.DefaultAvailableSeat holds the default value on creation for the available_seat field.
	flight.DefaultAvailableSeat = flightDescAvailableSeat.Default.(int)
	// flight.AvailableSeatValidator is a validator for the "available_seat" field. It is called by the builders before save.
	flight.AvailableSeatValidator = flightDescAvailableSeat.Validators[0].(func(int) error)
	// flightDescCreatedAt is the schema descriptor for created_at field.
	flightDescCreatedAt := flightFields[10].Descriptor()
	// flight.DefaultCreatedAt holds the default value on creation for the created_at field.
	flight.DefaultCreatedAt = flightDescCreatedAt.Default.(func() time.Time)
	// flightDescUpdatedAt is the schema descriptor for updated_at field.
	flightDescUpdatedAt := flightFields[11].Descriptor()
	// flight.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flight.DefaultUpdatedAt = flightDescUpdatedAt.Default.(func() time.Time)
	// flight.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flight.UpdateDefaultUpdatedAt = flightDescUpdatedAt.UpdateDefault.(func() time.Time)
	// flightDescID is the schema descriptor for id field.
	flightDescID := flightFields[0].Descriptor()
	// flight.DefaultID holds the default value on creation for the id field.
	flight.DefaultID = flightDescID.Default.(func() uuid.UUID)
}
